"""
Full-object characterization net for PositionMatcher.match_positions().

Purpose (S5-1, refactor plan phase 3 "matcher — kontrakty", deepened):
freeze the COMPLETE MatchedPosition output (every field via dataclasses.asdict)
for every construction path in match_positions(), so the upcoming in-file
extraction (S5-2/S5-3) cannot silently drop or swap a field.

Why full-object and not close_reason + a few fields: the only failure mode of a
builder extraction is a field silently dropped or swapped. A 3-field assertion
cannot see that. The existing test_matcher_contract.py pins close_reason and the
3 PnL-source paths; this file pins the whole object across all ~22 sites.

Coverage gaps this closes (verified against the --parse gate, which runs with
--skip-meteora so meteora_results is always empty there): EVERY `if meteora_result:`
branch is dark under the baseline gate, and only one contract test ever passes
meteora_results. Here every meteora variant of every event loop is exercised.

Also pins two side effects not catchable by a close-only --parse fixture:
  - match_positions MUTATES the caller's resolved_addresses (rug + already_closed
    register addresses back into it).
  - matched_ids is a single accumulator threaded across all four loops in order
    (close -> rug -> failsafe -> already_closed); later loops skip pids seen
    earlier, EXCEPT the rug loop which does not dedup (close+rug same pid -> 2 rows).

EXPECTED was generated against the pre-extraction code via:
    python tests/test_matcher_characterization.py
Do NOT regenerate it as part of an extraction change — that would make the net a
tautology. Regenerate only on a deliberate, reviewed behavior change.
"""

from dataclasses import asdict
from decimal import Decimal

import pytest

from valhalla.event_parser import EventParser
from valhalla.matcher import PositionMatcher
from valhalla.models import (
    AddLiquidityEvent,
    AlreadyClosedEvent,
    CloseEvent,
    FailsafeEvent,
    MeteoraPnlResult,
    OpenEvent,
    RugEvent,
)


DATE = "2026-04-26"
PID = "PID00001"


# --------------------------------------------------------------------------- #
# Event builders (mirror test_matcher_contract.py for consistency)
# --------------------------------------------------------------------------- #
def _open_event(pid=PID):
    return OpenEvent(
        timestamp="[10:00]",
        position_type="BidAsk",
        token_name="TOKEN",
        token_pair="TOKEN-SOL",
        target="wallet",
        market_cap=123.45,
        token_age="5h ago",
        jup_score=81,
        target_sol=1.0,
        your_sol=2.0,
        position_id=pid,
        date=DATE,
        target_wallet_address="OPENADDR",
        target_tx_signatures=["SIG1", "SIG2"],
    )


def _close_event(pid=PID, close_type="normal"):
    return CloseEvent(
        timestamp="[10:30]",
        target="wallet",
        starting_sol=10.0,
        starting_usd=100.0,
        ending_sol=13.0,
        ending_usd=130.0,
        position_id=pid,
        close_type=close_type,
        date=DATE,
    )


def _rug_event(pid=PID, position_address="ADDR"):
    return RugEvent(
        timestamp="[10:45]",
        target="wallet",
        token_pair="TOKEN-SOL",
        position_address=position_address,
        price_drop=25.0,
        threshold=20.0,
        position_id=pid,
        date=DATE,
    )


def _failsafe_event(pid=PID):
    return FailsafeEvent(timestamp="[10:50]", position_id=pid, date=DATE)


def _already_closed_event(pid=PID, position_address="ADDR"):
    return AlreadyClosedEvent(
        timestamp="[11:00]",
        position_id=pid,
        position_address=position_address,
        target="wallet",
        date=DATE,
    )


def _liq_event(pid=PID, amount_sol=0.5):
    return AddLiquidityEvent("[10:10]", pid, "wallet", amount_sol=amount_sol, date=DATE)


def _meteora_result():
    return MeteoraPnlResult(
        deposited_sol=Decimal("2.50"),
        withdrawn_sol=Decimal("3.10"),
        fees_sol=Decimal("0.20"),
        deposited_usd=Decimal("100"),
        withdrawn_usd=Decimal("120"),
        fees_usd=Decimal("8"),
        pnl_usd=Decimal("28"),
        pnl_sol=Decimal("0.70"),
    )


# --------------------------------------------------------------------------- #
# Scenario definitions: one per construction site + cross-loop interactions.
# Each value is the kwargs passed to _run().
# --------------------------------------------------------------------------- #
def _scenarios():
    met = {PID: _meteora_result()}
    return {
        # --- CLOSE loop ---
        "close_open_meteora": dict(opens=[_open_event()], closes=[_close_event()], meteora=met),
        "close_open_discord": dict(opens=[_open_event()], closes=[_close_event()], discord=True),
        "close_open_pending": dict(opens=[_open_event()], closes=[_close_event()]),
        "close_unknown_meteora": dict(closes=[_close_event()], meteora=met),
        "close_unknown_discord": dict(closes=[_close_event()], discord=True),
        "close_unknown_pending": dict(closes=[_close_event()]),
        # --- RUG loop (with position_id) ---
        "rug_open_meteora": dict(opens=[_open_event()], rugs=[_rug_event()], meteora=met),
        "rug_open_discord": dict(opens=[_open_event()], rugs=[_rug_event()], discord=True),
        "rug_open_pending": dict(opens=[_open_event()], rugs=[_rug_event()]),
        "rug_unknown_meteora": dict(rugs=[_rug_event()], meteora=met),
        "rug_unknown_discord": dict(rugs=[_rug_event()], discord=True),
        "rug_unknown_pending": dict(rugs=[_rug_event()]),
        # --- RUG loop (no position_id) ---
        "rug_nopid_discord": dict(rugs=[_rug_event(pid=None)], discord=True),
        "rug_nopid_pending": dict(rugs=[_rug_event(pid=None)]),
        # --- FAILSAFE loop (standalone) ---
        "failsafe_open_meteora": dict(opens=[_open_event()], failsafes=[_failsafe_event()], meteora=met),
        "failsafe_open_pending": dict(opens=[_open_event()], failsafes=[_failsafe_event()]),
        "failsafe_unknown_meteora": dict(failsafes=[_failsafe_event()], meteora=met),
        "failsafe_unknown_pending": dict(failsafes=[_failsafe_event()]),
        # --- ALREADY_CLOSED loop ---
        "ac_open_meteora": dict(opens=[_open_event()], already_closed=[_already_closed_event()], meteora=met),
        "ac_open_pending": dict(opens=[_open_event()], already_closed=[_already_closed_event()]),
        "ac_unknown_meteora": dict(already_closed=[_already_closed_event()], meteora=met),
        "ac_unknown_pending": dict(already_closed=[_already_closed_event()]),
        # --- close_reason variants on close loop ---
        "close_take_profit": dict(opens=[_open_event()], closes=[_close_event(close_type="take_profit")]),
        "close_stop_loss": dict(opens=[_open_event()], closes=[_close_event(close_type="stop_loss")]),
        "close_unknown_take_profit": dict(closes=[_close_event(close_type="take_profit")]),
        "close_unknown_stop_loss": dict(closes=[_close_event(close_type="stop_loss")]),
        # --- sol_deployed with extra liquidity (discord path uses it) ---
        "close_open_discord_with_liq": dict(
            opens=[_open_event()], closes=[_close_event()], add_liquidity=[_liq_event()], discord=True
        ),
        # --- CROSS-LOOP interactions ---
        # rug loop does NOT dedup -> close + rug same pid => 2 positions
        "xloop_close_then_rug_same_pid": dict(
            opens=[_open_event()], closes=[_close_event()], rugs=[_rug_event()]
        ),
        # failsafe seen before close -> failsafe_ids makes close_reason="failsafe"
        "xloop_failsafe_overrides_close_reason": dict(
            opens=[_open_event()], closes=[_close_event()], failsafes=[_failsafe_event()]
        ),
        # close handles pid -> failsafe + already_closed for same pid are skipped
        "xloop_dedup_close_failsafe_ac": dict(
            opens=[_open_event()],
            closes=[_close_event()],
            failsafes=[_failsafe_event()],
            already_closed=[_already_closed_event()],
        ),
        # rug registers its address into caller's resolved_addresses (pid absent)
        "xloop_rug_registers_address": dict(
            rugs=[_rug_event(position_address="RUGADDR")], resolved={}
        ),
        # already_closed registers its address into caller's resolved_addresses
        "xloop_ac_registers_address": dict(
            already_closed=[_already_closed_event(position_address="ACADDR")], resolved={}
        ),
    }


def _run(opens=(), closes=(), rugs=(), failsafes=(), already_closed=(),
         add_liquidity=(), meteora=None, discord=False, resolved=None):
    """Run matcher; return (matched_dicts, unmatched_ids, final_resolved_addresses)."""
    parser = EventParser(base_date=DATE)
    parser.open_events = list(opens)
    parser.close_events = list(closes)
    parser.rug_events = list(rugs)
    parser.failsafe_events = list(failsafes)
    parser.already_closed_events = list(already_closed)
    parser.add_liquidity_events = list(add_liquidity)

    resolved_addresses = dict(resolved) if resolved is not None else {PID: "RESOLVED"}

    matched, unmatched = PositionMatcher(parser).match_positions(
        meteora or {},
        resolved_addresses,
        use_discord_pnl=discord,
    )
    return (
        [asdict(p) for p in matched],
        [o.position_id for o in unmatched],
        resolved_addresses,
    )


# --------------------------------------------------------------------------- #
# Golden values — generated against pre-extraction code. See module docstring.
# --------------------------------------------------------------------------- #
EXPECTED = {'close_open_meteora': {'matched': [{'target_wallet': 'wallet',
                                     'token': 'TOKEN',
                                     'position_type': 'BidAsk',
                                     'sol_deployed': Decimal('2.50'),
                                     'sol_received': Decimal('3.10'),
                                     'pnl_sol': Decimal('0.70'),
                                     'pnl_pct': Decimal('28.00'),
                                     'close_reason': 'normal',
                                     'mc_at_open': 123.45,
                                     'jup_score': 81,
                                     'token_age': '5h ago',
                                     'token_age_days': 0,
                                     'token_age_hours': 5,
                                     'price_drop_pct': None,
                                     'position_id': 'PID00001',
                                     'full_address': 'RESOLVED',
                                     'pnl_source': 'meteora',
                                     'meteora_deposited': Decimal('2.50'),
                                     'meteora_withdrawn': Decimal('3.10'),
                                     'meteora_fees': Decimal('0.20'),
                                     'meteora_pnl': Decimal('0.70'),
                                     'datetime_open': '2026-04-26T10:00:00',
                                     'datetime_close': '2026-04-26T10:30:00',
                                     'target_wallet_address': 'OPENADDR',
                                     'target_tx_signature': 'SIG1',
                                     'source_wallet_hold_min': None,
                                     'source_wallet_pnl_pct': None,
                                     'source_wallet_scenario': None,
                                     'original_wallet': ''}],
                        'unmatched': [],
                        'resolved': {'PID00001': 'RESOLVED'}},
 'close_open_discord': {'matched': [{'target_wallet': 'wallet',
                                     'token': 'TOKEN',
                                     'position_type': 'BidAsk',
                                     'sol_deployed': Decimal('2.0'),
                                     'sol_received': Decimal('3.0'),
                                     'pnl_sol': Decimal('1.0'),
                                     'pnl_pct': Decimal('50.0'),
                                     'close_reason': 'normal',
                                     'mc_at_open': 123.45,
                                     'jup_score': 81,
                                     'token_age': '5h ago',
                                     'token_age_days': 0,
                                     'token_age_hours': 5,
                                     'price_drop_pct': None,
                                     'position_id': 'PID00001',
                                     'full_address': 'RESOLVED',
                                     'pnl_source': 'discord',
                                     'meteora_deposited': None,
                                     'meteora_withdrawn': None,
                                     'meteora_fees': None,
                                     'meteora_pnl': None,
                                     'datetime_open': '2026-04-26T10:00:00',
                                     'datetime_close': '2026-04-26T10:30:00',
                                     'target_wallet_address': 'OPENADDR',
                                     'target_tx_signature': 'SIG1',
                                     'source_wallet_hold_min': None,
                                     'source_wallet_pnl_pct': None,
                                     'source_wallet_scenario': None,
                                     'original_wallet': ''}],
                        'unmatched': [],
                        'resolved': {'PID00001': 'RESOLVED'}},
 'close_open_pending': {'matched': [{'target_wallet': 'wallet',
                                     'token': 'TOKEN',
                                     'position_type': 'BidAsk',
                                     'sol_deployed': None,
                                     'sol_received': None,
                                     'pnl_sol': None,
                                     'pnl_pct': None,
                                     'close_reason': 'normal',
                                     'mc_at_open': 123.45,
                                     'jup_score': 81,
                                     'token_age': '5h ago',
                                     'token_age_days': 0,
                                     'token_age_hours': 5,
                                     'price_drop_pct': None,
                                     'position_id': 'PID00001',
                                     'full_address': 'RESOLVED',
                                     'pnl_source': 'pending',
                                     'meteora_deposited': None,
                                     'meteora_withdrawn': None,
                                     'meteora_fees': None,
                                     'meteora_pnl': None,
                                     'datetime_open': '2026-04-26T10:00:00',
                                     'datetime_close': '2026-04-26T10:30:00',
                                     'target_wallet_address': 'OPENADDR',
                                     'target_tx_signature': 'SIG1',
                                     'source_wallet_hold_min': None,
                                     'source_wallet_pnl_pct': None,
                                     'source_wallet_scenario': None,
                                     'original_wallet': ''}],
                        'unmatched': [],
                        'resolved': {'PID00001': 'RESOLVED'}},
 'close_unknown_meteora': {'matched': [{'target_wallet': 'wallet',
                                        'token': 'unknown',
                                        'position_type': 'unknown',
                                        'sol_deployed': Decimal('2.50'),
                                        'sol_received': Decimal('3.10'),
                                        'pnl_sol': Decimal('0.70'),
                                        'pnl_pct': Decimal('28.00'),
                                        'close_reason': 'unknown_open',
                                        'mc_at_open': 0.0,
                                        'jup_score': 0,
                                        'token_age': '',
                                        'token_age_days': None,
                                        'token_age_hours': None,
                                        'price_drop_pct': None,
                                        'position_id': 'PID00001',
                                        'full_address': 'RESOLVED',
                                        'pnl_source': 'meteora',
                                        'meteora_deposited': Decimal('2.50'),
                                        'meteora_withdrawn': Decimal('3.10'),
                                        'meteora_fees': Decimal('0.20'),
                                        'meteora_pnl': Decimal('0.70'),
                                        'datetime_open': '',
                                        'datetime_close': '2026-04-26T10:30:00',
                                        'target_wallet_address': None,
                                        'target_tx_signature': None,
                                        'source_wallet_hold_min': None,
                                        'source_wallet_pnl_pct': None,
                                        'source_wallet_scenario': None,
                                        'original_wallet': ''}],
                           'unmatched': [],
                           'resolved': {'PID00001': 'RESOLVED'}},
 'close_unknown_discord': {'matched': [{'target_wallet': 'wallet',
                                        'token': 'unknown',
                                        'position_type': 'unknown',
                                        'sol_deployed': Decimal('0'),
                                        'sol_received': Decimal('3.0'),
                                        'pnl_sol': Decimal('3.0'),
                                        'pnl_pct': Decimal('0'),
                                        'close_reason': 'unknown_open',
                                        'mc_at_open': 0.0,
                                        'jup_score': 0,
                                        'token_age': '',
                                        'token_age_days': None,
                                        'token_age_hours': None,
                                        'price_drop_pct': None,
                                        'position_id': 'PID00001',
                                        'full_address': 'RESOLVED',
                                        'pnl_source': 'discord',
                                        'meteora_deposited': None,
                                        'meteora_withdrawn': None,
                                        'meteora_fees': None,
                                        'meteora_pnl': None,
                                        'datetime_open': '',
                                        'datetime_close': '2026-04-26T10:30:00',
                                        'target_wallet_address': None,
                                        'target_tx_signature': None,
                                        'source_wallet_hold_min': None,
                                        'source_wallet_pnl_pct': None,
                                        'source_wallet_scenario': None,
                                        'original_wallet': ''}],
                           'unmatched': [],
                           'resolved': {'PID00001': 'RESOLVED'}},
 'close_unknown_pending': {'matched': [{'target_wallet': 'wallet',
                                        'token': 'unknown',
                                        'position_type': 'unknown',
                                        'sol_deployed': None,
                                        'sol_received': None,
                                        'pnl_sol': None,
                                        'pnl_pct': None,
                                        'close_reason': 'unknown_open',
                                        'mc_at_open': 0.0,
                                        'jup_score': 0,
                                        'token_age': '',
                                        'token_age_days': None,
                                        'token_age_hours': None,
                                        'price_drop_pct': None,
                                        'position_id': 'PID00001',
                                        'full_address': 'RESOLVED',
                                        'pnl_source': 'pending',
                                        'meteora_deposited': None,
                                        'meteora_withdrawn': None,
                                        'meteora_fees': None,
                                        'meteora_pnl': None,
                                        'datetime_open': '',
                                        'datetime_close': '2026-04-26T10:30:00',
                                        'target_wallet_address': None,
                                        'target_tx_signature': None,
                                        'source_wallet_hold_min': None,
                                        'source_wallet_pnl_pct': None,
                                        'source_wallet_scenario': None,
                                        'original_wallet': ''}],
                           'unmatched': [],
                           'resolved': {'PID00001': 'RESOLVED'}},
 'rug_open_meteora': {'matched': [{'target_wallet': 'wallet',
                                   'token': 'TOKEN',
                                   'position_type': 'BidAsk',
                                   'sol_deployed': Decimal('2.50'),
                                   'sol_received': Decimal('3.10'),
                                   'pnl_sol': Decimal('0.70'),
                                   'pnl_pct': Decimal('28.00'),
                                   'close_reason': 'rug',
                                   'mc_at_open': 123.45,
                                   'jup_score': 81,
                                   'token_age': '5h ago',
                                   'token_age_days': 0,
                                   'token_age_hours': 5,
                                   'price_drop_pct': 25.0,
                                   'position_id': 'PID00001',
                                   'full_address': 'RESOLVED',
                                   'pnl_source': 'meteora',
                                   'meteora_deposited': Decimal('2.50'),
                                   'meteora_withdrawn': Decimal('3.10'),
                                   'meteora_fees': Decimal('0.20'),
                                   'meteora_pnl': Decimal('0.70'),
                                   'datetime_open': '2026-04-26T10:00:00',
                                   'datetime_close': '2026-04-26T10:45:00',
                                   'target_wallet_address': 'OPENADDR',
                                   'target_tx_signature': 'SIG1',
                                   'source_wallet_hold_min': None,
                                   'source_wallet_pnl_pct': None,
                                   'source_wallet_scenario': None,
                                   'original_wallet': ''}],
                      'unmatched': [],
                      'resolved': {'PID00001': 'RESOLVED'}},
 'rug_open_discord': {'matched': [{'target_wallet': 'wallet',
                                   'token': 'TOKEN',
                                   'position_type': 'BidAsk',
                                   'sol_deployed': Decimal('2.0'),
                                   'sol_received': Decimal('0'),
                                   'pnl_sol': Decimal('-0.50'),
                                   'pnl_pct': Decimal('-25.0'),
                                   'close_reason': 'rug',
                                   'mc_at_open': 123.45,
                                   'jup_score': 81,
                                   'token_age': '5h ago',
                                   'token_age_days': 0,
                                   'token_age_hours': 5,
                                   'price_drop_pct': 25.0,
                                   'position_id': 'PID00001',
                                   'full_address': 'RESOLVED',
                                   'pnl_source': 'discord',
                                   'meteora_deposited': None,
                                   'meteora_withdrawn': None,
                                   'meteora_fees': None,
                                   'meteora_pnl': None,
                                   'datetime_open': '2026-04-26T10:00:00',
                                   'datetime_close': '2026-04-26T10:45:00',
                                   'target_wallet_address': 'OPENADDR',
                                   'target_tx_signature': 'SIG1',
                                   'source_wallet_hold_min': None,
                                   'source_wallet_pnl_pct': None,
                                   'source_wallet_scenario': None,
                                   'original_wallet': ''}],
                      'unmatched': [],
                      'resolved': {'PID00001': 'RESOLVED'}},
 'rug_open_pending': {'matched': [{'target_wallet': 'wallet',
                                   'token': 'TOKEN',
                                   'position_type': 'BidAsk',
                                   'sol_deployed': Decimal('2.0'),
                                   'sol_received': None,
                                   'pnl_sol': None,
                                   'pnl_pct': None,
                                   'close_reason': 'rug',
                                   'mc_at_open': 123.45,
                                   'jup_score': 81,
                                   'token_age': '5h ago',
                                   'token_age_days': 0,
                                   'token_age_hours': 5,
                                   'price_drop_pct': 25.0,
                                   'position_id': 'PID00001',
                                   'full_address': 'RESOLVED',
                                   'pnl_source': 'pending',
                                   'meteora_deposited': None,
                                   'meteora_withdrawn': None,
                                   'meteora_fees': None,
                                   'meteora_pnl': None,
                                   'datetime_open': '2026-04-26T10:00:00',
                                   'datetime_close': '2026-04-26T10:45:00',
                                   'target_wallet_address': 'OPENADDR',
                                   'target_tx_signature': 'SIG1',
                                   'source_wallet_hold_min': None,
                                   'source_wallet_pnl_pct': None,
                                   'source_wallet_scenario': None,
                                   'original_wallet': ''}],
                      'unmatched': [],
                      'resolved': {'PID00001': 'RESOLVED'}},
 'rug_unknown_meteora': {'matched': [{'target_wallet': 'wallet',
                                      'token': 'unknown',
                                      'position_type': 'unknown',
                                      'sol_deployed': Decimal('2.50'),
                                      'sol_received': Decimal('3.10'),
                                      'pnl_sol': Decimal('0.70'),
                                      'pnl_pct': Decimal('28.00'),
                                      'close_reason': 'rug_unknown_open',
                                      'mc_at_open': 0.0,
                                      'jup_score': 0,
                                      'token_age': '',
                                      'token_age_days': None,
                                      'token_age_hours': None,
                                      'price_drop_pct': 25.0,
                                      'position_id': 'PID00001',
                                      'full_address': 'RESOLVED',
                                      'pnl_source': 'meteora',
                                      'meteora_deposited': Decimal('2.50'),
                                      'meteora_withdrawn': Decimal('3.10'),
                                      'meteora_fees': Decimal('0.20'),
                                      'meteora_pnl': Decimal('0.70'),
                                      'datetime_open': '',
                                      'datetime_close': '2026-04-26T10:45:00',
                                      'target_wallet_address': None,
                                      'target_tx_signature': None,
                                      'source_wallet_hold_min': None,
                                      'source_wallet_pnl_pct': None,
                                      'source_wallet_scenario': None,
                                      'original_wallet': ''}],
                         'unmatched': [],
                         'resolved': {'PID00001': 'RESOLVED'}},
 'rug_unknown_discord': {'matched': [{'target_wallet': 'wallet',
                                      'token': 'unknown',
                                      'position_type': 'unknown',
                                      'sol_deployed': Decimal('0'),
                                      'sol_received': Decimal('0'),
                                      'pnl_sol': Decimal('0'),
                                      'pnl_pct': Decimal('0'),
                                      'close_reason': 'rug_unknown_open',
                                      'mc_at_open': 0.0,
                                      'jup_score': 0,
                                      'token_age': '',
                                      'token_age_days': None,
                                      'token_age_hours': None,
                                      'price_drop_pct': 25.0,
                                      'position_id': 'PID00001',
                                      'full_address': 'RESOLVED',
                                      'pnl_source': 'discord',
                                      'meteora_deposited': None,
                                      'meteora_withdrawn': None,
                                      'meteora_fees': None,
                                      'meteora_pnl': None,
                                      'datetime_open': '',
                                      'datetime_close': '2026-04-26T10:45:00',
                                      'target_wallet_address': None,
                                      'target_tx_signature': None,
                                      'source_wallet_hold_min': None,
                                      'source_wallet_pnl_pct': None,
                                      'source_wallet_scenario': None,
                                      'original_wallet': ''}],
                         'unmatched': [],
                         'resolved': {'PID00001': 'RESOLVED'}},
 'rug_unknown_pending': {'matched': [{'target_wallet': 'wallet',
                                      'token': 'unknown',
                                      'position_type': 'unknown',
                                      'sol_deployed': None,
                                      'sol_received': None,
                                      'pnl_sol': None,
                                      'pnl_pct': None,
                                      'close_reason': 'rug_unknown_open',
                                      'mc_at_open': 0.0,
                                      'jup_score': 0,
                                      'token_age': '',
                                      'token_age_days': None,
                                      'token_age_hours': None,
                                      'price_drop_pct': 25.0,
                                      'position_id': 'PID00001',
                                      'full_address': 'RESOLVED',
                                      'pnl_source': 'pending',
                                      'meteora_deposited': None,
                                      'meteora_withdrawn': None,
                                      'meteora_fees': None,
                                      'meteora_pnl': None,
                                      'datetime_open': '',
                                      'datetime_close': '2026-04-26T10:45:00',
                                      'target_wallet_address': None,
                                      'target_tx_signature': None,
                                      'source_wallet_hold_min': None,
                                      'source_wallet_pnl_pct': None,
                                      'source_wallet_scenario': None,
                                      'original_wallet': ''}],
                         'unmatched': [],
                         'resolved': {'PID00001': 'RESOLVED'}},
 'rug_nopid_discord': {'matched': [{'target_wallet': 'wallet',
                                    'token': 'unknown',
                                    'position_type': 'unknown',
                                    'sol_deployed': Decimal('0'),
                                    'sol_received': Decimal('0'),
                                    'pnl_sol': Decimal('0'),
                                    'pnl_pct': Decimal('0'),
                                    'close_reason': 'rug_unknown_open',
                                    'mc_at_open': 0.0,
                                    'jup_score': 0,
                                    'token_age': '',
                                    'token_age_days': None,
                                    'token_age_hours': None,
                                    'price_drop_pct': 25.0,
                                    'position_id': '',
                                    'full_address': '',
                                    'pnl_source': 'discord',
                                    'meteora_deposited': None,
                                    'meteora_withdrawn': None,
                                    'meteora_fees': None,
                                    'meteora_pnl': None,
                                    'datetime_open': '',
                                    'datetime_close': '2026-04-26T10:45:00',
                                    'target_wallet_address': None,
                                    'target_tx_signature': None,
                                    'source_wallet_hold_min': None,
                                    'source_wallet_pnl_pct': None,
                                    'source_wallet_scenario': None,
                                    'original_wallet': ''}],
                       'unmatched': [],
                       'resolved': {'PID00001': 'RESOLVED'}},
 'rug_nopid_pending': {'matched': [{'target_wallet': 'wallet',
                                    'token': 'unknown',
                                    'position_type': 'unknown',
                                    'sol_deployed': None,
                                    'sol_received': None,
                                    'pnl_sol': None,
                                    'pnl_pct': None,
                                    'close_reason': 'rug_unknown_open',
                                    'mc_at_open': 0.0,
                                    'jup_score': 0,
                                    'token_age': '',
                                    'token_age_days': None,
                                    'token_age_hours': None,
                                    'price_drop_pct': 25.0,
                                    'position_id': '',
                                    'full_address': '',
                                    'pnl_source': 'pending',
                                    'meteora_deposited': None,
                                    'meteora_withdrawn': None,
                                    'meteora_fees': None,
                                    'meteora_pnl': None,
                                    'datetime_open': '',
                                    'datetime_close': '2026-04-26T10:45:00',
                                    'target_wallet_address': None,
                                    'target_tx_signature': None,
                                    'source_wallet_hold_min': None,
                                    'source_wallet_pnl_pct': None,
                                    'source_wallet_scenario': None,
                                    'original_wallet': ''}],
                       'unmatched': [],
                       'resolved': {'PID00001': 'RESOLVED'}},
 'failsafe_open_meteora': {'matched': [{'target_wallet': 'wallet',
                                        'token': 'TOKEN',
                                        'position_type': 'BidAsk',
                                        'sol_deployed': Decimal('2.50'),
                                        'sol_received': Decimal('3.10'),
                                        'pnl_sol': Decimal('0.70'),
                                        'pnl_pct': Decimal('28.00'),
                                        'close_reason': 'failsafe',
                                        'mc_at_open': 123.45,
                                        'jup_score': 81,
                                        'token_age': '5h ago',
                                        'token_age_days': 0,
                                        'token_age_hours': 5,
                                        'price_drop_pct': None,
                                        'position_id': 'PID00001',
                                        'full_address': 'RESOLVED',
                                        'pnl_source': 'meteora',
                                        'meteora_deposited': Decimal('2.50'),
                                        'meteora_withdrawn': Decimal('3.10'),
                                        'meteora_fees': Decimal('0.20'),
                                        'meteora_pnl': Decimal('0.70'),
                                        'datetime_open': '2026-04-26T10:00:00',
                                        'datetime_close': '2026-04-26T10:50:00',
                                        'target_wallet_address': 'OPENADDR',
                                        'target_tx_signature': 'SIG1',
                                        'source_wallet_hold_min': None,
                                        'source_wallet_pnl_pct': None,
                                        'source_wallet_scenario': None,
                                        'original_wallet': ''}],
                           'unmatched': [],
                           'resolved': {'PID00001': 'RESOLVED'}},
 'failsafe_open_pending': {'matched': [{'target_wallet': 'wallet',
                                        'token': 'TOKEN',
                                        'position_type': 'BidAsk',
                                        'sol_deployed': None,
                                        'sol_received': None,
                                        'pnl_sol': None,
                                        'pnl_pct': None,
                                        'close_reason': 'failsafe',
                                        'mc_at_open': 123.45,
                                        'jup_score': 81,
                                        'token_age': '5h ago',
                                        'token_age_days': 0,
                                        'token_age_hours': 5,
                                        'price_drop_pct': None,
                                        'position_id': 'PID00001',
                                        'full_address': 'RESOLVED',
                                        'pnl_source': 'pending',
                                        'meteora_deposited': None,
                                        'meteora_withdrawn': None,
                                        'meteora_fees': None,
                                        'meteora_pnl': None,
                                        'datetime_open': '2026-04-26T10:00:00',
                                        'datetime_close': '2026-04-26T10:50:00',
                                        'target_wallet_address': 'OPENADDR',
                                        'target_tx_signature': 'SIG1',
                                        'source_wallet_hold_min': None,
                                        'source_wallet_pnl_pct': None,
                                        'source_wallet_scenario': None,
                                        'original_wallet': ''}],
                           'unmatched': [],
                           'resolved': {'PID00001': 'RESOLVED'}},
 'failsafe_unknown_meteora': {'matched': [{'target_wallet': 'unknown',
                                           'token': 'unknown',
                                           'position_type': 'unknown',
                                           'sol_deployed': Decimal('2.50'),
                                           'sol_received': Decimal('3.10'),
                                           'pnl_sol': Decimal('0.70'),
                                           'pnl_pct': Decimal('28.00'),
                                           'close_reason': 'failsafe_unknown_open',
                                           'mc_at_open': 0.0,
                                           'jup_score': 0,
                                           'token_age': '',
                                           'token_age_days': None,
                                           'token_age_hours': None,
                                           'price_drop_pct': None,
                                           'position_id': 'PID00001',
                                           'full_address': 'RESOLVED',
                                           'pnl_source': 'meteora',
                                           'meteora_deposited': Decimal('2.50'),
                                           'meteora_withdrawn': Decimal('3.10'),
                                           'meteora_fees': Decimal('0.20'),
                                           'meteora_pnl': Decimal('0.70'),
                                           'datetime_open': '',
                                           'datetime_close': '2026-04-26T10:50:00',
                                           'target_wallet_address': None,
                                           'target_tx_signature': None,
                                           'source_wallet_hold_min': None,
                                           'source_wallet_pnl_pct': None,
                                           'source_wallet_scenario': None,
                                           'original_wallet': ''}],
                              'unmatched': [],
                              'resolved': {'PID00001': 'RESOLVED'}},
 'failsafe_unknown_pending': {'matched': [{'target_wallet': 'unknown',
                                           'token': 'unknown',
                                           'position_type': 'unknown',
                                           'sol_deployed': None,
                                           'sol_received': None,
                                           'pnl_sol': None,
                                           'pnl_pct': None,
                                           'close_reason': 'failsafe_unknown_open',
                                           'mc_at_open': 0.0,
                                           'jup_score': 0,
                                           'token_age': '',
                                           'token_age_days': None,
                                           'token_age_hours': None,
                                           'price_drop_pct': None,
                                           'position_id': 'PID00001',
                                           'full_address': 'RESOLVED',
                                           'pnl_source': 'pending',
                                           'meteora_deposited': None,
                                           'meteora_withdrawn': None,
                                           'meteora_fees': None,
                                           'meteora_pnl': None,
                                           'datetime_open': '',
                                           'datetime_close': '2026-04-26T10:50:00',
                                           'target_wallet_address': None,
                                           'target_tx_signature': None,
                                           'source_wallet_hold_min': None,
                                           'source_wallet_pnl_pct': None,
                                           'source_wallet_scenario': None,
                                           'original_wallet': ''}],
                              'unmatched': [],
                              'resolved': {'PID00001': 'RESOLVED'}},
 'ac_open_meteora': {'matched': [{'target_wallet': 'wallet',
                                  'token': 'TOKEN',
                                  'position_type': 'BidAsk',
                                  'sol_deployed': Decimal('2.50'),
                                  'sol_received': Decimal('3.10'),
                                  'pnl_sol': Decimal('0.70'),
                                  'pnl_pct': Decimal('28.00'),
                                  'close_reason': 'already_closed',
                                  'mc_at_open': 123.45,
                                  'jup_score': 81,
                                  'token_age': '5h ago',
                                  'token_age_days': 0,
                                  'token_age_hours': 5,
                                  'price_drop_pct': None,
                                  'position_id': 'PID00001',
                                  'full_address': 'RESOLVED',
                                  'pnl_source': 'meteora',
                                  'meteora_deposited': Decimal('2.50'),
                                  'meteora_withdrawn': Decimal('3.10'),
                                  'meteora_fees': Decimal('0.20'),
                                  'meteora_pnl': Decimal('0.70'),
                                  'datetime_open': '2026-04-26T10:00:00',
                                  'datetime_close': '2026-04-26T11:00:00',
                                  'target_wallet_address': 'OPENADDR',
                                  'target_tx_signature': 'SIG1',
                                  'source_wallet_hold_min': None,
                                  'source_wallet_pnl_pct': None,
                                  'source_wallet_scenario': None,
                                  'original_wallet': ''}],
                     'unmatched': [],
                     'resolved': {'PID00001': 'RESOLVED'}},
 'ac_open_pending': {'matched': [{'target_wallet': 'wallet',
                                  'token': 'TOKEN',
                                  'position_type': 'BidAsk',
                                  'sol_deployed': None,
                                  'sol_received': None,
                                  'pnl_sol': None,
                                  'pnl_pct': None,
                                  'close_reason': 'already_closed',
                                  'mc_at_open': 123.45,
                                  'jup_score': 81,
                                  'token_age': '5h ago',
                                  'token_age_days': 0,
                                  'token_age_hours': 5,
                                  'price_drop_pct': None,
                                  'position_id': 'PID00001',
                                  'full_address': 'RESOLVED',
                                  'pnl_source': 'pending',
                                  'meteora_deposited': None,
                                  'meteora_withdrawn': None,
                                  'meteora_fees': None,
                                  'meteora_pnl': None,
                                  'datetime_open': '2026-04-26T10:00:00',
                                  'datetime_close': '2026-04-26T11:00:00',
                                  'target_wallet_address': 'OPENADDR',
                                  'target_tx_signature': 'SIG1',
                                  'source_wallet_hold_min': None,
                                  'source_wallet_pnl_pct': None,
                                  'source_wallet_scenario': None,
                                  'original_wallet': ''}],
                     'unmatched': [],
                     'resolved': {'PID00001': 'RESOLVED'}},
 'ac_unknown_meteora': {'matched': [{'target_wallet': 'wallet',
                                     'token': 'unknown',
                                     'position_type': 'unknown',
                                     'sol_deployed': Decimal('2.50'),
                                     'sol_received': Decimal('3.10'),
                                     'pnl_sol': Decimal('0.70'),
                                     'pnl_pct': Decimal('28.00'),
                                     'close_reason': 'already_closed_unknown_open',
                                     'mc_at_open': 0.0,
                                     'jup_score': 0,
                                     'token_age': '',
                                     'token_age_days': None,
                                     'token_age_hours': None,
                                     'price_drop_pct': None,
                                     'position_id': 'PID00001',
                                     'full_address': 'RESOLVED',
                                     'pnl_source': 'meteora',
                                     'meteora_deposited': Decimal('2.50'),
                                     'meteora_withdrawn': Decimal('3.10'),
                                     'meteora_fees': Decimal('0.20'),
                                     'meteora_pnl': Decimal('0.70'),
                                     'datetime_open': '',
                                     'datetime_close': '2026-04-26T11:00:00',
                                     'target_wallet_address': None,
                                     'target_tx_signature': None,
                                     'source_wallet_hold_min': None,
                                     'source_wallet_pnl_pct': None,
                                     'source_wallet_scenario': None,
                                     'original_wallet': ''}],
                        'unmatched': [],
                        'resolved': {'PID00001': 'RESOLVED'}},
 'ac_unknown_pending': {'matched': [{'target_wallet': 'wallet',
                                     'token': 'unknown',
                                     'position_type': 'unknown',
                                     'sol_deployed': None,
                                     'sol_received': None,
                                     'pnl_sol': None,
                                     'pnl_pct': None,
                                     'close_reason': 'already_closed_unknown_open',
                                     'mc_at_open': 0.0,
                                     'jup_score': 0,
                                     'token_age': '',
                                     'token_age_days': None,
                                     'token_age_hours': None,
                                     'price_drop_pct': None,
                                     'position_id': 'PID00001',
                                     'full_address': 'RESOLVED',
                                     'pnl_source': 'pending',
                                     'meteora_deposited': None,
                                     'meteora_withdrawn': None,
                                     'meteora_fees': None,
                                     'meteora_pnl': None,
                                     'datetime_open': '',
                                     'datetime_close': '2026-04-26T11:00:00',
                                     'target_wallet_address': None,
                                     'target_tx_signature': None,
                                     'source_wallet_hold_min': None,
                                     'source_wallet_pnl_pct': None,
                                     'source_wallet_scenario': None,
                                     'original_wallet': ''}],
                        'unmatched': [],
                        'resolved': {'PID00001': 'RESOLVED'}},
 'close_take_profit': {'matched': [{'target_wallet': 'wallet',
                                    'token': 'TOKEN',
                                    'position_type': 'BidAsk',
                                    'sol_deployed': None,
                                    'sol_received': None,
                                    'pnl_sol': None,
                                    'pnl_pct': None,
                                    'close_reason': 'take_profit',
                                    'mc_at_open': 123.45,
                                    'jup_score': 81,
                                    'token_age': '5h ago',
                                    'token_age_days': 0,
                                    'token_age_hours': 5,
                                    'price_drop_pct': None,
                                    'position_id': 'PID00001',
                                    'full_address': 'RESOLVED',
                                    'pnl_source': 'pending',
                                    'meteora_deposited': None,
                                    'meteora_withdrawn': None,
                                    'meteora_fees': None,
                                    'meteora_pnl': None,
                                    'datetime_open': '2026-04-26T10:00:00',
                                    'datetime_close': '2026-04-26T10:30:00',
                                    'target_wallet_address': 'OPENADDR',
                                    'target_tx_signature': 'SIG1',
                                    'source_wallet_hold_min': None,
                                    'source_wallet_pnl_pct': None,
                                    'source_wallet_scenario': None,
                                    'original_wallet': ''}],
                       'unmatched': [],
                       'resolved': {'PID00001': 'RESOLVED'}},
 'close_stop_loss': {'matched': [{'target_wallet': 'wallet',
                                  'token': 'TOKEN',
                                  'position_type': 'BidAsk',
                                  'sol_deployed': None,
                                  'sol_received': None,
                                  'pnl_sol': None,
                                  'pnl_pct': None,
                                  'close_reason': 'stop_loss',
                                  'mc_at_open': 123.45,
                                  'jup_score': 81,
                                  'token_age': '5h ago',
                                  'token_age_days': 0,
                                  'token_age_hours': 5,
                                  'price_drop_pct': None,
                                  'position_id': 'PID00001',
                                  'full_address': 'RESOLVED',
                                  'pnl_source': 'pending',
                                  'meteora_deposited': None,
                                  'meteora_withdrawn': None,
                                  'meteora_fees': None,
                                  'meteora_pnl': None,
                                  'datetime_open': '2026-04-26T10:00:00',
                                  'datetime_close': '2026-04-26T10:30:00',
                                  'target_wallet_address': 'OPENADDR',
                                  'target_tx_signature': 'SIG1',
                                  'source_wallet_hold_min': None,
                                  'source_wallet_pnl_pct': None,
                                  'source_wallet_scenario': None,
                                  'original_wallet': ''}],
                     'unmatched': [],
                     'resolved': {'PID00001': 'RESOLVED'}},
 'close_unknown_take_profit': {'matched': [{'target_wallet': 'wallet',
                                            'token': 'unknown',
                                            'position_type': 'unknown',
                                            'sol_deployed': None,
                                            'sol_received': None,
                                            'pnl_sol': None,
                                            'pnl_pct': None,
                                            'close_reason': 'take_profit_unknown_open',
                                            'mc_at_open': 0.0,
                                            'jup_score': 0,
                                            'token_age': '',
                                            'token_age_days': None,
                                            'token_age_hours': None,
                                            'price_drop_pct': None,
                                            'position_id': 'PID00001',
                                            'full_address': 'RESOLVED',
                                            'pnl_source': 'pending',
                                            'meteora_deposited': None,
                                            'meteora_withdrawn': None,
                                            'meteora_fees': None,
                                            'meteora_pnl': None,
                                            'datetime_open': '',
                                            'datetime_close': '2026-04-26T10:30:00',
                                            'target_wallet_address': None,
                                            'target_tx_signature': None,
                                            'source_wallet_hold_min': None,
                                            'source_wallet_pnl_pct': None,
                                            'source_wallet_scenario': None,
                                            'original_wallet': ''}],
                               'unmatched': [],
                               'resolved': {'PID00001': 'RESOLVED'}},
 'close_unknown_stop_loss': {'matched': [{'target_wallet': 'wallet',
                                          'token': 'unknown',
                                          'position_type': 'unknown',
                                          'sol_deployed': None,
                                          'sol_received': None,
                                          'pnl_sol': None,
                                          'pnl_pct': None,
                                          'close_reason': 'stop_loss_unknown_open',
                                          'mc_at_open': 0.0,
                                          'jup_score': 0,
                                          'token_age': '',
                                          'token_age_days': None,
                                          'token_age_hours': None,
                                          'price_drop_pct': None,
                                          'position_id': 'PID00001',
                                          'full_address': 'RESOLVED',
                                          'pnl_source': 'pending',
                                          'meteora_deposited': None,
                                          'meteora_withdrawn': None,
                                          'meteora_fees': None,
                                          'meteora_pnl': None,
                                          'datetime_open': '',
                                          'datetime_close': '2026-04-26T10:30:00',
                                          'target_wallet_address': None,
                                          'target_tx_signature': None,
                                          'source_wallet_hold_min': None,
                                          'source_wallet_pnl_pct': None,
                                          'source_wallet_scenario': None,
                                          'original_wallet': ''}],
                             'unmatched': [],
                             'resolved': {'PID00001': 'RESOLVED'}},
 'close_open_discord_with_liq': {'matched': [{'target_wallet': 'wallet',
                                              'token': 'TOKEN',
                                              'position_type': 'BidAsk',
                                              'sol_deployed': Decimal('2.5'),
                                              'sol_received': Decimal('3.0'),
                                              'pnl_sol': Decimal('0.5'),
                                              'pnl_pct': Decimal('20.0'),
                                              'close_reason': 'normal',
                                              'mc_at_open': 123.45,
                                              'jup_score': 81,
                                              'token_age': '5h ago',
                                              'token_age_days': 0,
                                              'token_age_hours': 5,
                                              'price_drop_pct': None,
                                              'position_id': 'PID00001',
                                              'full_address': 'RESOLVED',
                                              'pnl_source': 'discord',
                                              'meteora_deposited': None,
                                              'meteora_withdrawn': None,
                                              'meteora_fees': None,
                                              'meteora_pnl': None,
                                              'datetime_open': '2026-04-26T10:00:00',
                                              'datetime_close': '2026-04-26T10:30:00',
                                              'target_wallet_address': 'OPENADDR',
                                              'target_tx_signature': 'SIG1',
                                              'source_wallet_hold_min': None,
                                              'source_wallet_pnl_pct': None,
                                              'source_wallet_scenario': None,
                                              'original_wallet': ''}],
                                 'unmatched': [],
                                 'resolved': {'PID00001': 'RESOLVED'}},
 'xloop_close_then_rug_same_pid': {'matched': [{'target_wallet': 'wallet',
                                                'token': 'TOKEN',
                                                'position_type': 'BidAsk',
                                                'sol_deployed': None,
                                                'sol_received': None,
                                                'pnl_sol': None,
                                                'pnl_pct': None,
                                                'close_reason': 'normal',
                                                'mc_at_open': 123.45,
                                                'jup_score': 81,
                                                'token_age': '5h ago',
                                                'token_age_days': 0,
                                                'token_age_hours': 5,
                                                'price_drop_pct': None,
                                                'position_id': 'PID00001',
                                                'full_address': 'RESOLVED',
                                                'pnl_source': 'pending',
                                                'meteora_deposited': None,
                                                'meteora_withdrawn': None,
                                                'meteora_fees': None,
                                                'meteora_pnl': None,
                                                'datetime_open': '2026-04-26T10:00:00',
                                                'datetime_close': '2026-04-26T10:30:00',
                                                'target_wallet_address': 'OPENADDR',
                                                'target_tx_signature': 'SIG1',
                                                'source_wallet_hold_min': None,
                                                'source_wallet_pnl_pct': None,
                                                'source_wallet_scenario': None,
                                                'original_wallet': ''},
                                               {'target_wallet': 'wallet',
                                                'token': 'TOKEN',
                                                'position_type': 'BidAsk',
                                                'sol_deployed': Decimal('2.0'),
                                                'sol_received': None,
                                                'pnl_sol': None,
                                                'pnl_pct': None,
                                                'close_reason': 'rug',
                                                'mc_at_open': 123.45,
                                                'jup_score': 81,
                                                'token_age': '5h ago',
                                                'token_age_days': 0,
                                                'token_age_hours': 5,
                                                'price_drop_pct': 25.0,
                                                'position_id': 'PID00001',
                                                'full_address': 'RESOLVED',
                                                'pnl_source': 'pending',
                                                'meteora_deposited': None,
                                                'meteora_withdrawn': None,
                                                'meteora_fees': None,
                                                'meteora_pnl': None,
                                                'datetime_open': '2026-04-26T10:00:00',
                                                'datetime_close': '2026-04-26T10:45:00',
                                                'target_wallet_address': 'OPENADDR',
                                                'target_tx_signature': 'SIG1',
                                                'source_wallet_hold_min': None,
                                                'source_wallet_pnl_pct': None,
                                                'source_wallet_scenario': None,
                                                'original_wallet': ''}],
                                   'unmatched': [],
                                   'resolved': {'PID00001': 'RESOLVED'}},
 'xloop_failsafe_overrides_close_reason': {'matched': [{'target_wallet': 'wallet',
                                                        'token': 'TOKEN',
                                                        'position_type': 'BidAsk',
                                                        'sol_deployed': None,
                                                        'sol_received': None,
                                                        'pnl_sol': None,
                                                        'pnl_pct': None,
                                                        'close_reason': 'failsafe',
                                                        'mc_at_open': 123.45,
                                                        'jup_score': 81,
                                                        'token_age': '5h ago',
                                                        'token_age_days': 0,
                                                        'token_age_hours': 5,
                                                        'price_drop_pct': None,
                                                        'position_id': 'PID00001',
                                                        'full_address': 'RESOLVED',
                                                        'pnl_source': 'pending',
                                                        'meteora_deposited': None,
                                                        'meteora_withdrawn': None,
                                                        'meteora_fees': None,
                                                        'meteora_pnl': None,
                                                        'datetime_open': '2026-04-26T10:00:00',
                                                        'datetime_close': '2026-04-26T10:30:00',
                                                        'target_wallet_address': 'OPENADDR',
                                                        'target_tx_signature': 'SIG1',
                                                        'source_wallet_hold_min': None,
                                                        'source_wallet_pnl_pct': None,
                                                        'source_wallet_scenario': None,
                                                        'original_wallet': ''}],
                                           'unmatched': [],
                                           'resolved': {'PID00001': 'RESOLVED'}},
 'xloop_dedup_close_failsafe_ac': {'matched': [{'target_wallet': 'wallet',
                                                'token': 'TOKEN',
                                                'position_type': 'BidAsk',
                                                'sol_deployed': None,
                                                'sol_received': None,
                                                'pnl_sol': None,
                                                'pnl_pct': None,
                                                'close_reason': 'failsafe',
                                                'mc_at_open': 123.45,
                                                'jup_score': 81,
                                                'token_age': '5h ago',
                                                'token_age_days': 0,
                                                'token_age_hours': 5,
                                                'price_drop_pct': None,
                                                'position_id': 'PID00001',
                                                'full_address': 'RESOLVED',
                                                'pnl_source': 'pending',
                                                'meteora_deposited': None,
                                                'meteora_withdrawn': None,
                                                'meteora_fees': None,
                                                'meteora_pnl': None,
                                                'datetime_open': '2026-04-26T10:00:00',
                                                'datetime_close': '2026-04-26T10:30:00',
                                                'target_wallet_address': 'OPENADDR',
                                                'target_tx_signature': 'SIG1',
                                                'source_wallet_hold_min': None,
                                                'source_wallet_pnl_pct': None,
                                                'source_wallet_scenario': None,
                                                'original_wallet': ''}],
                                   'unmatched': [],
                                   'resolved': {'PID00001': 'RESOLVED'}},
 'xloop_rug_registers_address': {'matched': [{'target_wallet': 'wallet',
                                              'token': 'unknown',
                                              'position_type': 'unknown',
                                              'sol_deployed': None,
                                              'sol_received': None,
                                              'pnl_sol': None,
                                              'pnl_pct': None,
                                              'close_reason': 'rug_unknown_open',
                                              'mc_at_open': 0.0,
                                              'jup_score': 0,
                                              'token_age': '',
                                              'token_age_days': None,
                                              'token_age_hours': None,
                                              'price_drop_pct': 25.0,
                                              'position_id': 'PID00001',
                                              'full_address': 'RUGADDR',
                                              'pnl_source': 'pending',
                                              'meteora_deposited': None,
                                              'meteora_withdrawn': None,
                                              'meteora_fees': None,
                                              'meteora_pnl': None,
                                              'datetime_open': '',
                                              'datetime_close': '2026-04-26T10:45:00',
                                              'target_wallet_address': None,
                                              'target_tx_signature': None,
                                              'source_wallet_hold_min': None,
                                              'source_wallet_pnl_pct': None,
                                              'source_wallet_scenario': None,
                                              'original_wallet': ''}],
                                 'unmatched': [],
                                 'resolved': {'PID00001': 'RUGADDR'}},
 'xloop_ac_registers_address': {'matched': [{'target_wallet': 'wallet',
                                             'token': 'unknown',
                                             'position_type': 'unknown',
                                             'sol_deployed': None,
                                             'sol_received': None,
                                             'pnl_sol': None,
                                             'pnl_pct': None,
                                             'close_reason': 'already_closed_unknown_open',
                                             'mc_at_open': 0.0,
                                             'jup_score': 0,
                                             'token_age': '',
                                             'token_age_days': None,
                                             'token_age_hours': None,
                                             'price_drop_pct': None,
                                             'position_id': 'PID00001',
                                             'full_address': 'ACADDR',
                                             'pnl_source': 'pending',
                                             'meteora_deposited': None,
                                             'meteora_withdrawn': None,
                                             'meteora_fees': None,
                                             'meteora_pnl': None,
                                             'datetime_open': '',
                                             'datetime_close': '2026-04-26T11:00:00',
                                             'target_wallet_address': None,
                                             'target_tx_signature': None,
                                             'source_wallet_hold_min': None,
                                             'source_wallet_pnl_pct': None,
                                             'source_wallet_scenario': None,
                                             'original_wallet': ''}],
                                'unmatched': [],
                                'resolved': {'PID00001': 'ACADDR'}}}

@pytest.mark.parametrize("name", sorted(_scenarios().keys()))
def test_match_positions_characterization(name):
    kwargs = _scenarios()[name]
    matched, unmatched, resolved = _run(**kwargs)
    golden = EXPECTED[name]
    assert matched == golden["matched"], f"matched mismatch for {name}"
    assert unmatched == golden["unmatched"], f"unmatched mismatch for {name}"
    assert resolved == golden["resolved"], f"resolved_addresses mismatch for {name}"


def test_every_scenario_has_golden():
    """Guard: if a scenario is added without regenerating EXPECTED, fail loudly."""
    assert sorted(_scenarios().keys()) == sorted(EXPECTED.keys())


if __name__ == "__main__":
    # Generator: emit the EXPECTED literal from current behavior.
    import pprint

    result = {}
    for name, kwargs in _scenarios().items():
        matched, unmatched, resolved = _run(**kwargs)
        result[name] = {"matched": matched, "unmatched": unmatched, "resolved": resolved}

    print("EXPECTED = " + pprint.pformat(result, width=100, sort_dicts=False))
